---
blank_issues_enabled: true
contact_links:
  - about: "ì„œë²„ìª½ì˜ ë¬¸ì œê°€ ì˜ì‹¬ë˜ì‹œë‚˜ìš”? ë‹¤ìŒ ë ˆí¬ì§€í† ë¦¬ì—ì„œ ì´ìŠˆë¥¼ ë‚¨ê²¨ì£¼ì„¸ìš” ğŸ™Œ"
    name: "Backend Repository"
    url: "https://github.com/withfig/autocomplete/issues/new/choose"
  - about: "í•„ìš”í•œ ì‚¬í•­ë“¤ì€ ì–¸ì œë“ ì§€ ë©”ì¼ë¡œ ë³´ë‚´ì£¼ì„¸ìš”. ìš”ì²­ì„ ìµœëŒ€í•œ ë„ì™€ë“œë¦´ê²Œìš” ğŸ™†ğŸ»ğŸ™†ğŸ»â€â™€ï¸"
    name: "ğŸ“© Email"
    url: "https://tinyurl.com/seeyouletter-report"
  - about: "ë§Œì•½ ë¬¸ì œê°€ ë°œìƒí•˜ëŠ” ê±°ë¼ë©´, ê°™ì€ ì´ìŠˆê°€ ìˆëŠ”ì§€ í™•ì¸í•  ìˆ˜ ìˆì–´ìš”! ğŸ«¶ğŸ»"
    name: "ğŸ’¬ Now Seeyouletter's Issues"
    url: "https://github.com/seeyouletter/seeyouletter-fe/issues"